### ISSUE TITLE
Code cleanup issues in forms

### ISSUE THREAD

**Issue by jonahgraham** [eclipse/january-forms#4]
Here are a number of code cleanup things that needs to be done in forms. Not a priority list, just stuff I happened to notice:

- [x] releng projects are the same names as top-level january (e.g. org.eclipse.january.releng.p2 exists in both eclipse/january and eclipse/january-forms)
- [x] .DS_Store in root of repo. Is that meant to be there?
- [x] january-local2 is the project name of the root project, can it be something like january-forms-root?
- [x] there are > 100 javadoc references to org.eclipse.ice.datastructures.* that should be updated
- [x] there is one reference to org.eclipse.ice.datastructures in non-comments org.eclipse.january.form.test/src/org/eclipse/january/datastructures/test/IJAXBClassProviderTester.java

**Comment by jayjaybillings** [comment]
Thanks Jonah. @SmithRWORNL said he will jump on this.

**Comment by jonahgraham** [comment]
@SmithRWORNL Thanks for the cleanup
